project:
  type: website

website:
  title: "Maxim Tatarchenko"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: united
    css: styles.css
    toc: true



