---
title: "Learning to generate chairs, tables and cars with convolutional networks"
type: "proceeding"
author: "A. Dosovitskiy, J. T. Springenberg, M. Tatarchenko, and T. Brox"
year: "2017"
publication: "TPAMI"
pdf: "https://lmb.informatik.uni-freiburg.de/Publications/2017/DTB17/Chairs_PAMI.pdf"
project: ""
code: ""
toc: false
---

## Abstract

We train generative 'up-convolutional' neural networks which are able to generate images of objects given object style, viewpoint, and color. We train the networks on rendered 3D models of chairs, tables, and cars. Our experiments show that the networks do not merely learn all images by heart, but rather find a meaningful representation of 3D models allowing them to assess the similarity of different models, interpolate between given views to generate the missing ones, extrapolate views, and invent new objects not present in the training set by recombining training instances, or even two different object classes. Moreover, we show that such generative networks can be used to find correspondences between different objects from the dataset, outperforming existing approaches on this task.

## Bibtex
```
@misc{dosovitskiy17tpami_chairs,
      title={Learning to generate chairs, tables and cars with convolutional networks}, 
      author={Alexey Dosovitskiy and Jost Tobias Springenberg and Maxim Tatarchenko and Thomas Brox},
      year={2017},
      booktitle={TPAMI}
}
```
