---
title: "Accurate Training Data for Occupancy Map Prediction in Automated Driving Using Evidence Theory"
type: "proceeding"
author: "J. Kälble, S. Wirges, M. Tatarchenko and E. Ilg"
year: "2024"
publication: "CVPR"
pdf: "https://arxiv.org/pdf/2405.10575"
project: ""
code: "https://github.com/boschresearch/evidential-occupancy"
toc: false
---

## Abstract

Automated driving fundamentally requires knowledge about the surrounding geometry of the scene. Modern approaches use only captured images to predict occupancy maps that represent the geometry. Training these approaches requires accurate data that may be acquired with the help of LiDAR scanners. We show that the techniques used for current benchmarks and training datasets to convert LiDAR scans into occupancy grid maps yield very low quality, and subsequently present a novel approach using evidence theory that yields more accurate reconstructions. We demonstrate that these are superior by a large margin, both qualitatively and quantitatively, and that we additionally obtain meaningful uncertainty estimates. When converting the occupancy maps back to depth estimates and comparing them with the raw LiDAR measurements, our method yields a MAE improvement of 30% to 52% on nuScenes and 53% on Waymo over other occupancy ground-truth data. Finally, we use the improved occupancy maps to train a state-of-the-art occupancy prediction method and demonstrate that it improves the MAE by 25% on nuScenes.

## Bibtex
```
@misc{kaelble24cvpr_binocc,
      title={Accurate Training Data for Occupancy Map Prediction in Automated Driving Using Evidence Theory}, 
      author={Jonas Kälble and Sascha Wirges and Maxim Tatarchenko and Eddy Ilg},
      year={2024},
      booktitle={CVPR}
}
```
