---
title: "Self-supervised 3d shape and viewpoint estimation from single images"
type: "proceeding"
author: "O. Mees, M. Tatarchenko, T. Brox and W. Burgard"
year: "2019"
publication: "IROS"
pdf: "https://arxiv.org/pdf/1910.07948.pdf"
project: ""
code: ""
toc: false
---

## Abstract

We present a convolutional neural network for joint 3D shape prediction and viewpoint estimation from a single input image. During training, our network gets the learning signal from a silhouette of an object in the input image - a form of self-supervision. It does not require ground truth data for 3D shapes and the viewpoints. Because it relies on such a weak form of supervision, our approach can easily be applied to real-world data. We demonstrate that our method produces reasonable qualitative and quantitative results on natural images for both shape estimation and viewpoint prediction. Unlike previous approaches, our method does not require multiple views of the same object instance in the dataset, which significantly expands the applicability in practical robotics scenarios. We showcase it by using the hallucinated shapes to improve the performance on the task of grasping real-world objects both in simulation and with a PR2 robot.

## Bibtex
```
@misc{mees19iros_3d,
      title={Self-supervised 3d shape and viewpoint estimation from single images}, 
      author={Oier Mees and Maxim Tatarchenko and Thomas Brox and Wolfram Burgard},
      year={2019},
      booktitle={IROS}
}
```
