---
title: "Semi-supervised semantic segmentation with high- and low-level consistency"
type: "proceeding"
author: "S. Mittal, M. Tatarchenko and T. Brox"
year: "2019"
publication: "TPAMI"
pdf: "https://arxiv.org/pdf/1908.05724.pdf"
project: ""
code: ""
toc: false
---

## Abstract

The ability to understand visual information from limited labeled data is an important aspect of machine learning. While image-level classification has been extensively studied in a semi-supervised setting, dense pixel-level classification with limited data has only drawn attention recently. In this work, we propose an approach for semi-supervised semantic segmentation that learns from limited pixel-wise annotated samples while exploiting additional annotation-free images. It uses two network branches that link semi-supervised classification with semi-supervised segmentation including self-training. The dual-branch approach reduces both the low-level and the high-level artifacts typical when training with few labels. The approach attains significant improvement over existing methods, especially when trained with very few labeled samples. On several standard benchmarks - PASCAL VOC 2012, PASCAL-Context, and Cityscapes - the approach achieves new state-of-the-art in semi-supervised learning.

## Bibtex
```
@misc{mittal19tpami,
      title={Semi-supervised semantic segmentation with high- and low-level consistency}, 
      author={Sudhanshu Mittal and Maxim Tatarchenko and Thomas Brox},
      year={2019},
      booktitle={TPAMI}
}
```
