---
title: "Tangent convolutions for dense prediction in 3D"
type: "proceeding"
author: "M. Tatarchenko, J. Park, V. Koltun, and Q.-Y. Zhou"
year: "2018"
publication: "CVPR"
pdf: "https://arxiv.org/pdf/1807.02443.pdf"
project: "http://vladlen.info/publications/tangent-convolutions-dense-prediction-3d/"
code: "https://github.com/tatarchm/tangent_conv"
toc: false
---

## Abstract

We present an approach to semantic scene analysis using deep convolutional networks. Our approach is based on tangent convolutions - a new construction for convolutional networks on 3D data. In contrast to volumetric approaches, our method operates directly on surface geometry. Crucially, the construction is applicable to unstructured point clouds and other noisy real-world data. We show that tangent convolutions can be evaluated efficiently on large-scale point clouds with millions of points. Using tangent convolutions, we design a deep fully-convolutional network for semantic segmentation of 3D point clouds, and apply it to challenging real-world datasets of indoor and outdoor 3D environments. Experimental results show that the presented approach outperforms other recent deep network constructions in detailed analysis of large 3D scenes.

## Bibtex
```
@misc{tatarchenko18cvpr_tangentconv,
      title={Tangent convolutions for dense prediction in 3D}, 
      author={Maxim Tatarchenko and Jaesik Park and Vladlen Koltun and Qian-Yi Zhou},
      year={2018},
      booktitle={CVPR}
}
```
