---
title: "Octree generating networks: Efficient convolutional architectures for high-resolution 3d outputs"
type: "proceeding"
author: "M. Tatarchenko, A. Dosovitskiy, and T. Brox"
year: "2017"
publication: "ICCV"
pdf: "https://arxiv.org/pdf/1703.09438.pdf"
project: "https://lmb.informatik.uni-freiburg.de/people/tatarchm/ogn/"
code: "https://github.com/lmb-freiburg/ogn"
toc: false
---

## Abstract

We present a deep convolutional decoder architecture that can generate volumetric 3D outputs in a compute- and memory-efficient manner by using an octree representation. The network learns to predict both the structure of the octree, and the occupancy values of individual cells. This makes it a particularly valuable technique for generating 3D shapes. In contrast to standard decoders acting on regular voxel grids, the architecture does not have cubic complexity. This allows representing much higher resolution outputs with a limited memory budget. We demonstrate this in several application domains, including 3D convolutional autoencoders, generation of objects and whole scenes from high-level representations, and shape from a single image.

## Bibtex
```
@misc{tatarchenko17iccv_ogn,
      title={Octree generating networks: Efficient convolutional architectures for high-resolution 3d outputs}, 
      author={Maxim Tatarchenko and Alexey Dosovitskiy and Thomas Brox},
      year={2017},
      booktitle={ICCV}
}
```
