---
title: "Image semantic segmentation of indoor scenes: A survey"
type: "proceeding"
author: "R. Velastegui, M. Tatarchenko, S. Karaoğlu and T. Gevers"
year: "2024"
publication: "CVIU"
pdf: "https://pdf.sciencedirectassets.com/271018/1-s2.0-S1077314224X00090/1-s2.0-S1077314224001838/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEPv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQDOejEZyey8zTP7eI84D6IMxfbBiyv2mYzOE1H2%2FuCs3AIgAXpgHBYzXRCnIdvHu74bhMW1tfB4liDXKhzShbkaZBYqvAUIpP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAFGgwwNTkwMDM1NDY4NjUiDKCqTfOKfxzL8TlwjSqQBZKZ1hdz3bzVlSNttXSPhYxQ0JYDh%2BetmWlGfh%2FdodGKzW2iCk1qhS7mcxEPyl%2B5tBHi8OTqC1TxzoXPDN9SVQ5Jmgq5TreZhWcWQ%2FyfV0EXcs2%2BOSoth1a20tTkPUzy0ev7IxHX%2Fb5auz4BgNxfsQGYHfmrR1rfdi8GvUDBtDh7Y8QvgDrf1F5nvn94vef0HWqgoiWEv1nZ1XiLgWuDk86lWi9%2BkMEbl2pn37RJprW%2FthYQqh3Ngfn5xKoOynk86vwPtiQz3O6nqxpZtISe26NmCTcd9yel9bM9cm4oQrBOx7PLW1hldFrlw0Ia4hE0NUY31Rf2inCFiRPThFDSoXG96ohJnFMeZiUd%2FB2nGszhCC%2BjMTaYv9F0AQg9E8E%2FNwtCIzO8a1cw%2BFn9n8PslmhosWmlwzK4OtLR3AUfSPM9U6FGbm7eexl2rnbD3Xe7clPSsqo4pJZMf9HaQDacoFABnp5Gw1iBU3gVAAan6mHaxdXmYyijT3TwDc27255%2FH40OS2BxKUuYsaL%2B9dFSFu1JWZZacbn3vEYyU6OIRw7%2BdD3Ec32bXPx3JnTv6B83QmHLhOHFhNzdjjHLGh8W5Nj0C%2BGFwixYw0fJH94qiPBDSUD9VLjDVVXE8iDzqG%2FQ3nrCZb3NcM0h5aeKE2cOeCHAoCfsf7O4RFjd8h6eaZ0uzSY9xXCeH1%2FVyp2YnO%2B6c6O2AdNOVwOv%2FSP8SKbCAFkPGMP7pJezLZbds4x6Sjg0PwxDM0r8z8umDPHNnvMtkLzMNi3oKiuy5Awcrnz0PevDLEXQYm5ueE9XgR5PgJLByG4qxHriWiAFTrMnri4KNVy3HIc81e4OWBcy8M0fvGA5OP7%2Bt%2FKsXCjVxJZjcz9aMMn%2BsLoGOrEBL1ZltufEYaJHb6%2B3gbT2vOqie1JM6VVidTQFKx%2BPP%2FLv5l%2FSiM7la6%2FKA%2Fr7sk5v5HUeR%2B5UYuX2Hu9u2UnVtgyNWzO5SyVz%2FoeovAwBaFb%2F3A6xKjQc6wOO4fXPYCYw3sUjOXnqLf31V0WCPXshpJG3%2BUSVA3Lq1R43iLy8yx2fSFL8Dku5rH5dIZIN2qFZjTdIprRxg1ekbccJnnvPWNfI8ue%2B7QKHb5rjKhXgJRPW&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241201T114542Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTY5GKE63VJ%2F20241201%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=b37348726d9b1f31d5d3473fe52c65b6aca739663b1b852c01507c711d685c37&hash=3766ef230be6d4ceabc407534c5208a5bb80888673f19f59c73f18f5bf9dca1b&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S1077314224001838&tid=spdf-baf6ec07-6e6e-433c-b39a-124123ed8dc3&sid=c8b420195cd3b448f74baa5261eb83a7b506gxrqb&type=client&tsoh=d3d3LnNjaWVuY2VkaXJlY3QuY29t&ua=1e03590a025607555150&rr=8eb2d521bbabe507&cc=de"
project: ""
code: ""
toc: false
---

## Abstract

This survey provides a comprehensive evaluation of various deep learning-based segmentation architectures.
It covers a wide range of models, from traditional ones like FCN and PSPNet to more modern approaches like
SegFormer and FAN. In addition to assessing the methods in terms of segmentation accuracy, we propose
to also evaluate the methods in terms of temporal consistency and corruption vulnerability. Most of the
existing surveys on semantic segmentation focus on outdoor datasets. In contrast, this survey focuses on
indoor scenarios to enhance the applicability of segmentation methods in this specific domain. Furthermore,
our evaluation consists of a performance analysis of the methods in prevalent real-world segmentation
scenarios that pose particular challenges. These complex situations involve scenes impacted by diverse forms of
noise, blur corruptions, camera movements, optical aberrations, among other factors. By jointly exploring the
segmentation accuracy, temporal consistency, and corruption vulnerability in challenging real-world situations,
our survey offers insights that go beyond existing surveys, facilitating the understanding and development of
better image segmentation methods for indoor scenes.

## Bibtex
```
@misc{velastegui24cviu_semseg,
      title={Image semantic segmentation of indoor scenes: A survey}, 
      author={Ronny Velastegui and Maxim Tatarchenko and Sezer Karaoglu and Theo Gevers},
      year={2024},
      booktitle={CVIU}
}
```
